// <auto-generated />
using System;
using MFBAdminMBlazorServer.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MFBAdminMBlazorServer.Migrations
{
    [DbContext(typeof(web_nprtsContext))]
    [Migration("20210413120007_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:Collation", "Cyrillic_General_BIN")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MFBAdminMBlazorServer.Models.MfbDisclosureFirstPartItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ItemCode")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("item_code");

                    b.Property<string>("ItemDescription")
                        .HasMaxLength(1024)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1024)")
                        .HasColumnName("item_description");

                    b.Property<int>("ItemShowFlags")
                        .HasColumnType("int")
                        .HasColumnName("item_show_flags");

                    b.Property<DateTime?>("Now")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("now")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("RegulationCode")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("regulation_code");

                    b.Property<int?>("Seq")
                        .HasColumnType("int")
                        .HasColumnName("seq");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<string>("Username")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("username")
                        .HasDefaultValueSql("(suser_sname())");

                    b.HasKey("Id");

                    b.ToTable("mfb_disclosure_first_part_item");
                });

            modelBuilder.Entity("MFBAdminMBlazorServer.Models.MfbDisclosureFirstPartItemList", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("DateFrom")
                        .HasColumnType("date")
                        .HasColumnName("date_from");

                    b.Property<DateTime?>("DateTo")
                        .HasColumnType("date")
                        .HasColumnName("date_to");

                    b.Property<long>("Idp")
                        .HasColumnType("bigint")
                        .HasColumnName("idp");

                    b.Property<string>("ItemListCategory")
                        .HasMaxLength(1024)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1024)")
                        .HasColumnName("item_list_category");

                    b.Property<string>("ItemListDesc")
                        .HasMaxLength(2048)
                        .IsUnicode(false)
                        .HasColumnType("varchar(2048)")
                        .HasColumnName("item_list_desc");

                    b.Property<int?>("ItemListType")
                        .HasColumnType("int")
                        .HasColumnName("item_list_type");

                    b.Property<string>("ItemListValue")
                        .HasMaxLength(4096)
                        .IsUnicode(false)
                        .HasColumnType("varchar(4096)")
                        .HasColumnName("item_list_value");

                    b.Property<string>("Memo")
                        .HasMaxLength(1024)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1024)")
                        .HasColumnName("memo");

                    b.Property<DateTime?>("Now")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("now")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("PublishMoment")
                        .HasColumnType("datetime")
                        .HasColumnName("publish_moment");

                    b.Property<int?>("Seq")
                        .HasColumnType("int")
                        .HasColumnName("seq");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<string>("Username")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("username")
                        .HasDefaultValueSql("(suser_sname())");

                    b.HasKey("Id");

                    b.HasIndex("Idp");

                    b.ToTable("mfb_disclosure_first_part_item_list");
                });

            modelBuilder.Entity("MFBAdminMBlazorServer.Models.MfbDisclosureSecondPartItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateFrom")
                        .HasColumnType("date")
                        .HasColumnName("date_from");

                    b.Property<DateTime?>("DateTo")
                        .HasColumnType("date")
                        .HasColumnName("date_to");

                    b.Property<string>("ExtraDetails")
                        .HasMaxLength(4096)
                        .IsUnicode(false)
                        .HasColumnType("varchar(4096)")
                        .HasColumnName("extra_details");

                    b.Property<int>("Frequency")
                        .HasColumnType("int")
                        .HasColumnName("frequency");

                    b.Property<string>("ItemCode")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("item_code");

                    b.Property<string>("ItemDescription")
                        .HasMaxLength(1024)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1024)")
                        .HasColumnName("item_description");

                    b.Property<string>("ItemNumber")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("item_number");

                    b.Property<int>("ItemType")
                        .HasColumnType("int")
                        .HasColumnName("item_type");

                    b.Property<string>("ItemValue")
                        .HasMaxLength(4096)
                        .IsUnicode(false)
                        .HasColumnType("varchar(4096)")
                        .HasColumnName("item_value");

                    b.Property<DateTime?>("Now")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("now")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("PublishMoment")
                        .HasColumnType("datetime")
                        .HasColumnName("publish_moment");

                    b.Property<string>("RegulationCode")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("regulation_code");

                    b.Property<int?>("Seq")
                        .HasColumnType("int")
                        .HasColumnName("seq");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<string>("Username")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("username")
                        .HasDefaultValueSql("(suser_sname())");

                    b.HasKey("Id");

                    b.ToTable("mfb_disclosure_second_part_item");
                });

            modelBuilder.Entity("MFBAdminMBlazorServer.Models.MfbDisclosureSecondPartItemList", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("Idp")
                        .HasColumnType("bigint")
                        .HasColumnName("idp");

                    b.Property<string>("ItemListCategory")
                        .HasMaxLength(1024)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1024)")
                        .HasColumnName("item_list_category");

                    b.Property<string>("ItemListDesc")
                        .HasMaxLength(2048)
                        .IsUnicode(false)
                        .HasColumnType("varchar(2048)")
                        .HasColumnName("item_list_desc");

                    b.Property<int?>("ItemListType")
                        .HasColumnType("int")
                        .HasColumnName("item_list_type");

                    b.Property<string>("ItemListValue")
                        .HasMaxLength(4096)
                        .IsUnicode(false)
                        .HasColumnType("varchar(4096)")
                        .HasColumnName("item_list_value");

                    b.Property<int?>("Seq")
                        .HasColumnType("int")
                        .HasColumnName("seq");

                    b.HasKey("Id");

                    b.HasIndex("Idp");

                    b.ToTable("mfb_disclosure_second_part_item_list");
                });

            modelBuilder.Entity("MFBAdminMBlazorServer.Models.MfbFineRate", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AssetCode")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)")
                        .HasColumnName("asset_code");

                    b.Property<string>("AssetIsin")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)")
                        .HasColumnName("asset_isin");

                    b.Property<string>("AssetName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("asset_name");

                    b.Property<decimal?>("BaseLimit")
                        .HasColumnType("numeric(16,6)")
                        .HasColumnName("base_limit");

                    b.Property<decimal?>("BaseLimitSurprise")
                        .HasColumnType("numeric(16,6)")
                        .HasColumnName("base_limit_surprise");

                    b.Property<string>("CurrencyCode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("currency_code");

                    b.Property<string>("CurrencyName")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasColumnName("currency_name");

                    b.Property<decimal?>("FineLongDonor")
                        .HasColumnType("numeric(16,6)")
                        .HasColumnName("fine_long_donor");

                    b.Property<decimal?>("FineLongGuilty")
                        .HasColumnType("numeric(16,6)")
                        .HasColumnName("fine_long_guilty");

                    b.Property<decimal?>("FineLongVictim")
                        .HasColumnType("numeric(16,6)")
                        .HasColumnName("fine_long_victim");

                    b.Property<decimal?>("FineShortDonor")
                        .HasColumnType("numeric(16,6)")
                        .HasColumnName("fine_short_donor");

                    b.Property<decimal?>("FineShortGuilty")
                        .HasColumnType("numeric(16,6)")
                        .HasColumnName("fine_short_guilty");

                    b.Property<decimal?>("FineShortVictim")
                        .HasColumnType("numeric(16,6)")
                        .HasColumnName("fine_short_victim");

                    b.Property<string>("GroupName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("group_name");

                    b.Property<decimal?>("MrStress")
                        .HasColumnType("numeric(16,6)")
                        .HasColumnName("mr_stress");

                    b.Property<DateTime?>("ReportDate")
                        .HasColumnType("date")
                        .HasColumnName("report_date");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "ReportDate" }, "IX_mfb_fine_rate_report_date");

                    b.ToTable("mfb_fine_rate");
                });

            modelBuilder.Entity("MFBAdminMBlazorServer.Models.MfbFineRateHist", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AssetCode")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)")
                        .HasColumnName("asset_code");

                    b.Property<string>("AssetIsin")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)")
                        .HasColumnName("asset_isin");

                    b.Property<string>("AssetName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("asset_name");

                    b.Property<decimal?>("BaseLimit")
                        .HasColumnType("numeric(16,6)")
                        .HasColumnName("base_limit");

                    b.Property<decimal?>("BaseLimitSurprise")
                        .HasColumnType("numeric(16,6)")
                        .HasColumnName("base_limit_surprise");

                    b.Property<string>("CurrencyCode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("currency_code");

                    b.Property<string>("CurrencyName")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasColumnName("currency_name");

                    b.Property<decimal?>("FineLongDonor")
                        .HasColumnType("numeric(16,6)")
                        .HasColumnName("fine_long_donor");

                    b.Property<decimal?>("FineLongGuilty")
                        .HasColumnType("numeric(16,6)")
                        .HasColumnName("fine_long_guilty");

                    b.Property<decimal?>("FineLongVictim")
                        .HasColumnType("numeric(16,6)")
                        .HasColumnName("fine_long_victim");

                    b.Property<decimal?>("FineShortDonor")
                        .HasColumnType("numeric(16,6)")
                        .HasColumnName("fine_short_donor");

                    b.Property<decimal?>("FineShortGuilty")
                        .HasColumnType("numeric(16,6)")
                        .HasColumnName("fine_short_guilty");

                    b.Property<decimal?>("FineShortVictim")
                        .HasColumnType("numeric(16,6)")
                        .HasColumnName("fine_short_victim");

                    b.Property<string>("GroupName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("group_name");

                    b.Property<decimal?>("MrStress")
                        .HasColumnType("numeric(16,6)")
                        .HasColumnName("mr_stress");

                    b.Property<DateTime?>("ReportDate")
                        .HasColumnType("date")
                        .HasColumnName("report_date");

                    b.HasKey("Id");

                    b.ToTable("mfb_fine_rate_hist");
                });

            modelBuilder.Entity("MFBAdminMBlazorServer.Models.MfbDisclosureFirstPartItemList", b =>
                {
                    b.HasOne("MFBAdminMBlazorServer.Models.MfbDisclosureFirstPartItem", "IdpNavigation")
                        .WithMany("MfbDisclosureFirstPartItemLists")
                        .HasForeignKey("Idp")
                        .HasConstraintName("FK_mfb_disclosure_first_part_item_list_mfb_disclosure_first_part_item")
                        .IsRequired();

                    b.Navigation("IdpNavigation");
                });

            modelBuilder.Entity("MFBAdminMBlazorServer.Models.MfbDisclosureSecondPartItemList", b =>
                {
                    b.HasOne("MFBAdminMBlazorServer.Models.MfbDisclosureSecondPartItem", "IdpNavigation")
                        .WithMany("MfbDisclosureSecondPartItemLists")
                        .HasForeignKey("Idp")
                        .HasConstraintName("FK_mfb_disclosure_second_part_item_list_mfb_disclosure_second_part_item")
                        .IsRequired();

                    b.Navigation("IdpNavigation");
                });

            modelBuilder.Entity("MFBAdminMBlazorServer.Models.MfbDisclosureFirstPartItem", b =>
                {
                    b.Navigation("MfbDisclosureFirstPartItemLists");
                });

            modelBuilder.Entity("MFBAdminMBlazorServer.Models.MfbDisclosureSecondPartItem", b =>
                {
                    b.Navigation("MfbDisclosureSecondPartItemLists");
                });
#pragma warning restore 612, 618
        }
    }
}
